# Generated by Django 5.2.12 on 2026-09-30

from decimal import Decimal

import django.core.validators
import django.db.models.functions.text
import maintenance.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_maintenancerecord_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancerecord",
            name="maintenance_date",
            field=models.DateField(
                validators=[maintenance.validators.validate_not_future_date]
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerecord",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="mechanic",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("certification_number"),
                name="unique_mechanic_certification_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost__gte", 0)),
                name="maintenance_record_cost_non_negative",
            ),
        ),
    ]
